import { CheckboxChangeEvent } from "primereact/checkbox";
import React from "react";
import { TextPanels } from "./TextPanels";
import { ToggleTextPanels } from "./ToggleTextPanels";

type TextComponentProps = {
  panels: string[];
};

export type Text = {
  views: Record<string, string[]>;
};

export const TextComponent = (props: TextComponentProps) => {
  const [panels, setPanels] = React.useState(props.panels);
  const text: Text = {
    views: {
      textNL: [
        "Beste ",
        "Zus",
        ",",
        "\n",
        "",
        "kom ",
        "je ",
        "morgenavond ",
        "(",
        "Woensdag",
        ") ",
        "om ",
        "kwart ",
        "voor ",
        "acht ",
        "ingang ",
        "kleine ",
        "zaal ",
        "Concertgebouw",
        "",
        ", ",
        " ",
        "dan ",
        "heb ",
        "ik ",
        "een ",
        "plaats ",
        "voor ",
        "v ",
        "",
        ". ",
        " ",
        "Bu",
        "l",
        "h",
        "lig ",
        "voor ",
        "je",
        ".",
        "",
        "En ",
        "dan ",
        "kunnen ",
        "we ",
        "een ",
        "andere ",
        "dan ",
        "Donderdagmiddag ",
        "afspreken ",
        "want ",
        "dan ",
        "kan ",
        "ik ",
        "niet ",
        "goed",
        ".",
        "\n",
        "Met ",
        "vele ",
        "beste ",
        "groeten ",
        "je ",
        "Piet",
        ".",
        "\n",
      ],
      textEN: [
        "Dear ",
        "Zus",
        ",",
        "",
        "\n",
        "",
        "If ",
        "you ",
        "come ",
        "to ",
        "the ",
        "entrance ",
        "to ",
        "the ",
        "small ",
        "auditorium ",
        "in ",
        "the ",
        "Concertgebouw ",
        "at ",
        "a ",
        "quarter ",
        "to ",
        "eight ",
        "tomorrow ",
        "(",
        "Wednesday",
        ") ",
        "evening",
        ", ",
        "I ",
        "have ",
        "a ",
        "ticket ",
        "for ",
        "van ",
        "Buhlig ",
        "for ",
        "you",
        ".",
        "",
        "And ",
        "then ",
        "we ",
        "can ",
        "arrange ",
        "a ",
        "time ",
        "other ",
        "than ",
        "Thursday ",
        "afternoon ",
        "because ",
        "I ",
        "ca",
        "n’t ",
        "manage ",
        "that",
        ".",
        "\n",
        "With ",
        "my ",
        "very ",
        "best ",
        "wishes",
        ", ",
        "your ",
        "Piet",
        ".",
        "\n",
      ],
      textNotes: [
        "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui.",
      ],
      textFull: [
        "",
        "Brief ",
        "aan ",
        "Aletta ",
        "de ",
        "Iongh",
        ". ",
        "Amsterdam",
        ", ",
        "dinsdag ",
        "16 ",
        "februari",
        ", ",
        "dinsdag ",
        "2 ",
        "maart ",
        "of ",
        "dinsdag ",
        "9 ",
        "maart ",
        "1909",
        ".",
        "\n",
        "Wietse ",
        "Coppes",
        "\n",
        "Leo ",
        "Jansen",
        "\n",
        "Mondriaan ",
        "Editieproject",
        "\n",
        "\n",
        "Nederland",
        "\n",
        "Otterlo",
        "\n",
        "Kröller ",
        "Müller ",
        "Museum",
        "\n",
        "KM ",
        "123.397",
        "\n",
        "19090216y_IONG_1303",
        "\n",
        "",
        "\n",
        "",
        "",
        "\n",
        "\n",
        "Piet ",
        "Mondriaan",
        "\n",
        "dinsdag ",
        "16 ",
        "februari",
        ", ",
        "dinsdag ",
        "2 ",
        "maart ",
        "of ",
        "dinsdag ",
        "9 ",
        "maart ",
        "1909",
        "\n",
        "Amsterdam",
        "\n",
        "Aletta ",
        "de ",
        "Iongh",
        "\n",
        "\n",
        "transcriptie",
        ": ",
        "voltooid ",
        "20.7.15",
        "\n",
        "collatie ",
        "bron",
        ": ",
        "6.6.16",
        "\n",
        "tweede ",
        "collatie ",
        "aan ",
        "het ",
        "origineel",
        ": ",
        "voltooid ",
        "26.11.19",
        "\n",
        "invoer ",
        "tweede ",
        "collatie",
        ": ",
        "voltooid ",
        "5.8.16",
        "\n",
        "bespreking ",
        "eindversie",
        ": ",
        "gb",
        "\n",
        "markeren ",
        "annotaties",
        ": ",
        "in ",
        "bewerking ",
        "/ ",
        "voltooid",
        "\n",
        "gereed ",
        "17.4.2019",
        "\n",
        "titel ",
        "gecontroleerd ",
        "21.09.2020",
        "\n",
        "personen ",
        "getagd ",
        "12.10.2020",
        "\n",
        "vertaling ",
        "ingevoerd ",
        "16.2.2021",
        "\n",
        "codering ",
        "personen ",
        "aangepast ",
        "16.2.2022",
        "\n",
        "controle",
        "/",
        "aanpassing ",
        "afkortingen ",
        "en ",
        "emendaties ",
        "21.4.2023",
        "\n",
        "\n",
        "",
        "",
        "\n",
        "",
        "\n",
        "",
        "\n",
        "",
        "\n",
        "\n",
        "Beste ",
        "Zus",
        ",",
        "\n",
        "",
        "kom ",
        "je ",
        "morgenavond ",
        "(",
        "Woensdag",
        ") ",
        "om ",
        "kwart ",
        "voor ",
        "acht ",
        "ingang ",
        "kleine ",
        "zaal ",
        "Concertgebouw",
        "",
        ", ",
        " ",
        "dan ",
        "heb ",
        "ik ",
        "een ",
        "plaats ",
        "voor ",
        "v ",
        "",
        ". ",
        " ",
        "Bu",
        "l",
        "h",
        "lig ",
        "voor ",
        "je",
        ".",
        "",
        "En ",
        "dan ",
        "kunnen ",
        "we ",
        "een ",
        "andere ",
        "dan ",
        "Donderdagmiddag ",
        "afspreken ",
        "want ",
        "dan ",
        "kan ",
        "ik ",
        "niet ",
        "goed",
        ".",
        "\n",
        "Met ",
        "vele ",
        "beste ",
        "groeten ",
        "je ",
        "Piet",
        ".",
        "\n",
        "\n",
        "Dear ",
        "Zus",
        ",",
        "",
        "\n",
        "",
        "If ",
        "you ",
        "come ",
        "to ",
        "the ",
        "entrance ",
        "to ",
        "the ",
        "small ",
        "auditorium ",
        "in ",
        "the ",
        "Concertgebouw ",
        "at ",
        "a ",
        "quarter ",
        "to ",
        "eight ",
        "tomorrow ",
        "(",
        "Wednesday",
        ") ",
        "evening",
        ", ",
        "I ",
        "have ",
        "a ",
        "ticket ",
        "for ",
        "van ",
        "Buhlig ",
        "for ",
        "you",
        ".",
        "",
        "And ",
        "then ",
        "we ",
        "can ",
        "arrange ",
        "a ",
        "time ",
        "other ",
        "than ",
        "Thursday ",
        "afternoon ",
        "because ",
        "I ",
        "ca",
        "n’t ",
        "manage ",
        "that",
        ".",
        "\n",
        "With ",
        "my ",
        "very ",
        "best ",
        "wishes",
        ", ",
        "your ",
        "Piet",
        ".",
        "\n",
        "\n",
        "Manuscript",
        ".",
        "\n",
        "De ",
        "brief ",
        "is ",
        "geschreven ",
        "op ",
        "een ",
        "dinsdag ",
        "voorafgaand ",
        "aan ",
        "een ",
        "van ",
        "de ",
        "drie ",
        "woensdagen ",
        "waarop ",
        "Richard ",
        "Buhlig",
        " ",
        "in ",
        "1909 ",
        "in ",
        "de ",
        "kleine ",
        "zaal ",
        "van ",
        "het ",
        "Concertgebouw ",
        "een ",
        "concert ",
        "zou ",
        "geven",
        ": ",
        "17 ",
        "februari",
        ", ",
        "3 ",
        "maart ",
        "en ",
        "10 ",
        "maart",
        ". ",
        "Zie ",
        "tevens ",
        "n. ",
        '"',
        "plaatsBuhlig",
        '"',
        ".",
        "\n",
        "",
        "\n",
        "Aletta",
        " ",
        "werd ",
        "binnen ",
        "haar ",
        "familie ",
        "aangesproken ",
        "met ",
        "de ",
        "koosnaam ",
        "'",
        "Zus",
        "' ",
        "(",
        "Heteren ",
        "2018",
        ", ",
        "p. ",
        "25",
        ") ",
        "Mondriaans ",
        "gebruik ",
        "van ",
        "deze ",
        "naam ",
        "geeft ",
        "aan ",
        "dat ",
        "hij ",
        "op ",
        "intieme ",
        "voet ",
        "stond ",
        "met ",
        "De ",
        "Iongh",
        ".",
        "\n",
        "De ",
        "Amerikaanse ",
        "pianist ",
        "Richard ",
        "Moritz ",
        "Buhlig",
        " ",
        "(",
        "1880",
        "-",
        "1952",
        ") ",
        "gaf ",
        "begin ",
        "1909 ",
        "drie ",
        "concerten ",
        "in ",
        "de ",
        "kleine ",
        "zaal ",
        "van ",
        "het ",
        "Concertgebouw",
        ", ",
        "op ",
        "woensdag ",
        "17 ",
        "februari",
        ", ",
        "woensdag ",
        "3 ",
        "maart ",
        "en ",
        "woensdag ",
        "10 ",
        "maart",
        ". ",
        "Het ",
        "is ",
        "niet ",
        "bekend ",
        "voor ",
        "welke ",
        "van ",
        "deze ",
        "concerten ",
        "Mondriaan ",
        "kaarten ",
        "had",
        ".",
        "\n",
        "\n",
      ],
    },
  };

  function textPanelsCheckboxHandler(event: CheckboxChangeEvent) {
    const checkedTextPanels = [...panels];

    if (event.checked) {
      checkedTextPanels.push(event.value);
    } else {
      checkedTextPanels.splice(checkedTextPanels.indexOf(event.value), 1);
    }

    setPanels(checkedTextPanels);
  }

  function closePanelHandler(panelToClose: string) {
    setPanels(panels.filter((panel) => panel !== panelToClose));
  }

  return (
    <div className="textContainer">
      <ToggleTextPanels
        textPanelsCheckboxHandler={textPanelsCheckboxHandler}
        panels={panels}
      />
      <div className="textPanelsContainer">
        <TextPanels
          panels={panels}
          text={text}
          closePanelHandler={closePanelHandler}
        />
      </div>
    </div>
  );
};
