import { Labels } from "../../../model/Labels.tsx";

export const dutchLabels: Labels = {
  DATE_ASC: "Datum (oplopend)",
  DATE_DESC: "Datum (aflopend)",
  DISPLAY_CONTEXT: "Toon context",
  FROM: "Van",
  NEW_SEARCH_QUERY: "Nieuwe zoekopdracht",
  NEXT: "Volgende",
  NO_SEARCH_HISTORY: "Geen zoekgeschiedenis",
  PAGE_VIEW: "Page view",
  PREV: "Vorige",
  RELEVANCE: "Relevantie",
  RESULTS_PER_PAGE: "Resultaten per pagina",
  SEARCH_HISTORY: "Zoekgeschiedenis",
  SELECTED_FACETS: "Geselecteerde facets",
  SNIPPET: "Snippet",
  SORT_BY: "Sorteer op",
  TEXT: "Tekst",
  UP_TO_AND_INCLUDING: "Tot en met",
  FULL_TEXT_SEARCH: "Vrij zoeken",
  PRESS_ENTER_TO_SEARCH: "Druk op ENTER om te zoeken",
  RESULTS: "Resultaten",
  FILTERS: "Filters",

  JANUARY: "januari",
  FEBRUARY: "februari",
  MARCH: "maart",
  APRIL: "april",
  MAY: "mei",
  JUNE: "juni",
  JULY: "juli",
  AUGUST: "augustus",
  SEPTEMBER: "september",
  OCTOBER: "oktober",
  NOVEMBER: "november",
  DECEMBER: "december",

  METADATA: "Metadata",
  WEB_ANNOTATIONS: "Web annotations",

  SHOW_INFO: "Toon info",
  HIDE_INFO: "Verberg info",
  SHOW_FACSIMILE: "Toon facsimile",
  HIDE_FACSIMILE: "Verberg facsimile",
  SHOW_SEARCH_RESULTS: "Toon zoekresultaten",
  HIDE_SEARCH_RESULTS: "Verberg zoekresultaten",
  NEW_SEARCH: "Nieuwe zoekopdracht",

  NEXT_PAGE: "Volgende pagina",
  PREV_PAGE: "Vorige pagina",
  INFO_FIRST_PAGE: "U heeft de eerste pagina bereikt",
  INFO_LAST_PAGE: "U heeft de laatste pagina bereikt",

  NO_FACETS_FOUND: "Geen search facets gevonden",
  NO_INDICES_FOUND: "Geen zoek indices gevonden",
  NO_SEARCH_RESULTS:
    "Geen zoekresultaten. Probeer een andere combinatie van facetten.",

  DATE: "Datum",
};
