import { Labels } from "../../../model/Labels.tsx";

export const englishLabels: Labels = {
  DATE_ASC: "Date (ascending)",
  DATE_DESC: "Date (descending)",
  DATE_FROM: "From",
  DISPLAY_CONTEXT: "Display context",
  FROM: "Of",
  NEW_SEARCH_QUERY: "New search query",
  NEXT: "Next",
  NO_SEARCH_HISTORY: "No search history",
  PREV: "Prev",
  RELEVANCE: "Relevance",
  RESULTS_PER_PAGE: "Results per page",
  SEARCH_HISTORY: "Search history",
  SELECTED_FACETS: "Selected facets",
  SMALL: "Small",
  MEDIUM: "Medium",
  LARGE: "Large",
  SORT_BY: "Sort by",
  TEXT: "Text",
  UP_TO_AND_INCLUDING: "To",
  FULL_TEXT_SEARCH: "Full text search",
  PRESS_ENTER_TO_SEARCH: "Press ENTER to search",
  RESULTS: "Results",
  FILTERS: "Filters",
  FILTER_FACETS: "Filter facets",

  SHOW_MORE: "More",
  SHOW_LESS: "Less",

  RESET_DATE: "Reset date",
  LINE_CHART: "Line chart",
  BAR_CHART: "Bar chart",
  HIDE_HISTOGRAM: "Hide histogram",
  SHOW_HISTOGRAM: "Show histogram",

  JANUARY: "January",
  FEBRUARY: "February",
  MARCH: "March",
  APRIL: "April",
  MAY: "May",
  JUNE: "June",
  JULY: "July",
  AUGUST: "August",
  SEPTEMBER: "September",
  OCTOBER: "October",
  NOVEMBER: "November",
  DECEMBER: "December",

  METADATA: "Metadata",
  WEB_ANNOTATIONS: "Web annotations",

  SHOW_INFO: "Show info",
  HIDE_INFO: "Hide info",
  SHOW_FACSIMILE: "Show facsimile",
  HIDE_FACSIMILE: "Hide Facsimile",
  SHOW_SEARCH_RESULTS: "Show search results",
  HIDE_SEARCH_RESULTS: "Hide search results",
  NEW_SEARCH: "New search",
  BACK_TO_SEARCH: "Back to search results",
  PREV_RESULT: "Prev result",
  NEXT_RESULT: "Next result",

  NEXT_PAGE: "Next page",
  PREV_PAGE: "Previous page",
  INFO_FIRST_PAGE: "You have reached the first page",
  INFO_LAST_PAGE: "You have reached the last page",
  NEXT_SCAN: "Next scan",
  PREV_SCAN: "Prev scan",

  NO_FACETS_FOUND: "No search facets found",
  NO_INDICES_FOUND: "No search indices found",
  NO_SEARCH_RESULTS: "No results. Please try a different query.",
  NO_SEARCH_STRING:
    "No full-text keyword was specified. Please specify a search term.",

  DATE: "Date",

  SEARCH_CATEGORY: "Search for",
  WARNING_NEW_SEARCH: "Note: this will start a new search session",
  MORE_INFO_ON_CATEGORY: "More info on",

  // Help labels
  FULL_TEXT_SEARCH_HELP: "",
  SEARCH_HISTORY_HELP: "",
  SHOW_CONTEXT_HELP: "",
  SLIDER_FACET_HELP: "",
  FILTER_FACETS_HELP: "",
  SORT_BY_HELP: "",
  TOGGLE_INFO_HELP: "",

  OCCURRENCES_PER_YEAR: "Voorkomens per year",
};
