import {Labels} from '../../../model/Labels.tsx';

export const englishLabels: Labels = {
  DATE_ASC: 'Date (ascending)',
  DATE_DESC: 'Date (descending)',
  DISPLAY_CONTEXT: 'Display context',
  FROM: 'From',
  NEW_SEARCH_QUERY: 'New search query',
  NEXT: 'Next',
  NO_SEARCH_HISTORY: 'No search history',
  PAGE_VIEW: 'Page view',
  PREV: 'Prev',
  RELEVANCE: 'Relevance',
  RESULTS_PER_PAGE: 'Results per page',
  SEARCH_HISTORY: 'Search history',
  SELECTED_FACETS: 'Selected facets',
  SNIPPET: 'Snippet',
  SORT_BY: 'Sort by',
  TEXT: 'Text',
  UP_TO_AND_INCLUDING: 'Up to and including',

  JANUARY: 'January',
  FEBRUARY: 'February',
  MARCH: 'March',
  APRIL: 'April',
  MAY: 'May',
  JUNE: 'June',
  JULY: 'July',
  AUGUST: 'August',
  SEPTEMBER: 'September',
  OCTOBER: 'October',
  NOVEMBER: 'November',
  DECEMBER: 'December',

  METADATA: 'Metadata',
  WEB_ANNOTATIONS: 'Web annotations',

  SHOW_INFO: 'Show info',
  HIDE_INFO: 'Hide info',
  SHOW_FACSIMILE: 'Show facsimile',
  HIDE_FACSIMILE: 'Hide Facsimile',
  SHOW_SEARCH_RESULTS: 'Show search results',
  HIDE_SEARCH_RESULTS: 'Hide search results',
  NEW_SEARCH: 'New search',

  NEXT_PAGE: 'Next page',
  PREV_PAGE: 'Previous page',
  INFO_FIRST_PAGE: 'You have reached the first page',
  INFO_LAST_PAGE: 'You have reached the last page',
}