import {Labels} from "../../../../model/Labels.tsx";

export const dutchLabels: Labels = {
  DATE_ASC: "Datum (oplopend)",
  DATE_DESC: "Datum (aflopend)",
  DISPLAY_CONTEXT: "Toon context",
  FROM: "Van",
  NEW_SEARCH_QUERY: "Nieuwe zoekopdracht",
  NEXT: "Volgende",
  NO_SEARCH_HISTORY: "Geen zoekgeschiedenis",
  PAGE_VIEW: "Page view",
  PREV: "Vorige",
  RELEVANCE: "Relevantie",
  RESULTS_PER_PAGE: "Resultaten per pagina",
  SEARCH_HISTORY: "Zoekgeschiedenis",
  SELECTED_FACETS: "Geselecteerde facets",
  SNIPPET: "Snippet",
  SORT_BY: "Sorteer op",
  TEXT: "Tekst",
  UP_TO_AND_INCLUDING: "Tot en met",

  JANUARY: "januari",
  FEBRUARY: "februari",
  MARCH: "maart",
  APRIL: "april",
  MAY: "mei",
  JUNE: "juni",
  JULY: "juli",
  AUGUST: "augustus",
  SEPTEMBER: "september",
  OCTOBER: "oktober",
  NOVEMBER: "november",
  DECEMBER: "december",

  METADATA: 'Metadata',
  WEB_ANNOTATIONS: 'Web annotations',

  SHOW_INFO: "Toon info",
  HIDE_INFO: "Verberg info",
  SHOW_FACSIMILE: "Toon facsimile",
  HIDE_FACSIMILE: "Verberg facsimile",
  SHOW_SEARCH_RESULTS: "Toon zoekresultaten",
  HIDE_SEARCH_RESULTS: "Verberg zoekresultaten",
  NEW_SEARCH: "Nieuwe zoekopdracht",

}