import {Labels} from "../../../../model/Labels.tsx";

export const englishLabels: Labels = {
  DATE_ASC: "Date (ascending)",
  DATE_DESC: "Date (descending)",
  DISPLAY_CONTEXT: "Display context",
  FROM: "From",
  NEW_SEARCH_QUERY: "New search query",
  NEXT: "Next",
  NO_SEARCH_HISTORY: "No search history",
  PAGE_VIEW: "Page view",
  PREV: "Prev",
  RELEVANCE: "Relevance",
  RESULTS_PER_PAGE: "Results per page",
  SEARCH_HISTORY: "Search history",
  SELECTED_FACETS: "Selected facets",
  SNIPPET: "Snippet",
  SORT_BY: "Sort by",
  TEXT: "Text",
  UP_TO_AND_INCLUDING: "Up to and including",

  JANUARY: "January",
  FEBRUARY: "February",
  MARCH: "March",
  APRIL: "April",
  MAY: "May",
  JUNE: "June",
  JULY: "July",
  AUGUST: "August",
  SEPTEMBER: "September",
  OCTOBER: "October",
  NOVEMBER: "November",
  DECEMBER: "December",
}