server {
    listen 80;

    location = /app/config {
        alias /etc/nginx/config.json;
        default_type application/json;
    }

    location /app/ {
        proxy_pass http://tav:80/;
    }
}