import merge from "lodash/merge";
import logo from "../../../assets/logo-republic-temp.png";
import { TabRecipes } from "../../../components/Detail/TabRecipes";
import {
  ProjectConfig,
  ProjectSpecificConfig,
} from "../../../model/ProjectConfig";
import { defaultConfig } from "../../default/config";
import {
  getAnnotationCategory,
  getHighlightCategory,
  projectEntityTypes,
  projectHighlightedTypes,
  projectPageMarkerAnnotationTypes,
  projectTooltipMarkerAnnotationTypes,
} from "../annotation/ProjectAnnotationModel";
import { AnnotationButtons } from "../AnnotationButtons";
import { MetadataPanel } from "../MetadataPanel";
import projectCss from "../project.css?inline";
import { SearchItem } from "../SearchItem";
import { englishVanGoghLabels } from "./englishVanGoghLabels";

export const vangoghConfig: ProjectConfig = merge({}, defaultConfig, {
  id: "vangogh",
  broccoliUrl: "https://preview.dev.diginfra.org/broccoli",
  relativeTo: "tf:Letter",
  annotationTypesToInclude: [
    // "tei:About",
    // "tei:AltIdentifier",
    "tei:Artwork",
    "tei:Artworklist",
    // "tei:Availability",
    // "tei:Bibl",
    // "tei:Bibliolist",
    // "tei:Biolist",
    // "tei:Birth",
    // "tei:Body",
    // "tei:C",
    // "tei:Cell",
    // "tei:CorrespAction",
    // "tei:CorrespDesc",
    // "tei:Date",
    // "tei:Death",
    "tei:Div",
    // "tei:Editor",
    // "tei:Facsimile",
    // "tei:Figure",
    // "tei:FileDesc",
    // "tei:Forename",
    "tei:Graphic",
    "tei:Head",
    "tei:Hi",
    // "tei:Idno",
    // "tei:Institution",
    // "tei:Item",
    // "tei:Label",
    // "tei:Licence",
    // "tei:List",
    // "tei:ListAnnotation",
    // "tei:ListBibl",
    // "tei:ListObject",
    // "tei:ListPerson",
    // "tei:Measure",
    // "tei:MsDesc",
    // "tei:MsIdentifier",
    // "tei:Name",
    "tei:Note",
    // "tei:P",
    "tei:PersName",
    "tei:Person",
    // "tei:PlaceName",
    // "tei:ProfileDesc",
    "tei:Ptr",
    // "tei:PubPlace",
    // "tei:PublicationStmt",
    // "tei:Publisher",
    // "tei:Quote",
    // "tei:Ref",
    // "tei:Relation",
    // "tei:Row",
    "tei:Rs",
    // "tei:Settlement",
    // "tei:SourceDesc",
    "tei:Space",
    // "tei:StandOff",
    // "tei:Supplied",
    // "tei:Surface",
    // "tei:Surname",
    // "tei:Table",
    // "tei:TeiHeader",
    // "tei:Text",
    // "tei:Title",
    // "tei:TitleStmt",
    // "tei:Zone",
    "tf:File",
    "tf:Letter",
    "tf:Page",
    "tt:LetterBody",
  ],
  showAnnotations: true,
  highlightedAnnotationTypes: projectHighlightedTypes,
  tooltipMarkerAnnotationTypes: projectTooltipMarkerAnnotationTypes,
  pageMarkerAnnotationTypes: projectPageMarkerAnnotationTypes,
  entityAnnotationTypes: projectEntityTypes,
  getAnnotationCategory: getAnnotationCategory,
  getHighlightCategory: getHighlightCategory,

  elasticIndexName: "vangogh",
  initialDateFrom: "1600-01-01",
  initialDateTo: "2000-01-01",
  initialRangeFrom: "0",
  initialRangeTo: "30000",
  maxRange: 30000,
  logoImageUrl: logo,
  headerColor: "bg-brand1-100 text-brand1-700",
  headerTitle: "Correspondence of Vincent van Gogh",
  showSearchResultsButtonFooter: false,
  useExternalConfig: true,
  showToggleTextPanels: true,
  defaultKeywordAggsToRender: ["correspondent", "location", "period", "sender"],
  components: {
    SearchItem,
    MetadataPanel,
    AnnotationButtons,
  },
  selectedLanguage: "en",
  zoomAnnoMirador: true,
  languages: [{ code: "en", labels: englishVanGoghLabels }],
  detailPanels: [
    {
      name: "facs-text",
      tabs: [TabRecipes.facsTab, TabRecipes.textTab],
    },
    {
      name: "text-facs",
      tabs: [TabRecipes.textTab, TabRecipes.facsTab],
    },
    {
      name: "metadata-webannos",
      tabs: [TabRecipes.metadataTab, TabRecipes.webAnnoTab],
    },
  ],
  allPossibleTextPanels: ["self", "textOrig", "textTrans"],
  defaultTextPanels: ["textOrig"],
  projectCss: projectCss,
} as ProjectSpecificConfig);
