version: '3.8'

services:
  nginx:
    container_name: tav_nginx
    image: nginx:1.19
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nginx_network
      - elucidate_network
      - textrepo_network
    ports:
      - "8000:8000"

networks:
  nginx_network:
  elucidate_network:
    external: true
    name: elucidate_network
  textrepo_network:
    external: true
    name: textrepo_network
