#FROM node:lts-alpine AS build
FROM node:22.20-alpine AS build

WORKDIR /textannoviz
COPY ./package.json /textannoviz/package.json
COPY ./package-lock.json /textannoviz/package-lock.json

RUN npm install --force && npm ci --force

COPY . .
RUN npm test
RUN npm run build:prod

FROM nginx:stable-alpine-slim
COPY --from=build /textannoviz/dist /usr/share/nginx/html
COPY ./deploy/nginx/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
