export enum ACTIONS {
    SET_STORE = "SET_STORE",
    SET_MIRANN = "SET_MIRANN",
    SET_ANNO = "SET_ANNO",
    SET_TEXT = "SET_TEXT",
    SET_SELECTEDANN = "SET_SELECTEDANN",
    SET_BROCCOLI = "SET_BROCCOLI",
    SET_TEXTTOHIGHLIGHT = "SET_TEXTTOHIGHLIGHT",
    SET_ANNITEMOPEN = "SET_ANNITEMOPEN",
    SET_CURRENTCONTEXT = "SET_CURRENTCONTEXT"
}